## Milestone 1 EDA

### Read Raw Data

NOTE: Before running this, ensure that the `Patio_Lawn_and_Garden` dataset has been unpacked into `data/raw`.

In [2]:
import pandas as pd

## Create Samples of the Data

This is to view a small sample of the data so that we know what we are working with.

In [7]:
reviews_df = pd.read_json("../data/raw/Patio_Lawn_and_Garden.jsonl", lines = True, chunksize = 100)
metadata_df = pd.read_json("../data/raw/meta_Patio_Lawn_and_Garden.jsonl", lines = True, chunksize = 100)

In [8]:
first_reviews = next(reviews_df)
first_reviews.to_json("../data/processed/Patio_Lawn_and_Garden_sample.jsonl",orient='records', indent=4)
first_meta = next(metadata_df)
first_meta.to_json("../data/processed/meta_Patio_Lawn_and_Garden_sample.jsonl",orient='records', indent=4)

<positron-console-cell-8>:2: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.

In [9]:
first_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,1,Someone’s return? Arrived broken in several pl...,Seriously. Not my best month with Amazon. Open...,[{'small_image_url': 'https://images-na.ssl-im...,B00KGVWNRG,B07CL2CD4D,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2021-04-21 00:33:51.473,0,False
1,1,Arrived broken,The chair wouldn't fold out properly. The foot...,[],B00I4Z8GCM,B0C6HJPJXL,AGGZ357AO26RQZVRLGU4D4N52DZQ,2022-08-23 13:32:57.742,0,True
2,1,Disappointing,Bought this on a Cyber Monday deal and I'm so ...,[],B01CHG9MXA,B01CHG9MXA,AGGZ357AO26RQZVRLGU4D4N52DZQ,2016-12-13 21:46:16.000,0,True
3,3,Cute style but just ok- don't buy more than 1 ...,Bought these because of the unique look. I pur...,[],B004BK1DL0,B004BK1DL0,AGKASBHYZPGTEPO6LWZPVJWB2BVA,2022-05-21 23:03:26.096,1,True
4,5,Seriously I have tried just about everything. ...,Seriously I have tried just about everything. ...,[],B004CSWPS6,B004CSWPS6,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2016-09-17 20:36:07.000,0,False

In [10]:
first_meta.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Amazon Home,AISEN Carburetor AIR Filter Tune UP KIT for C1...,3.8,8,[Fits for Echo PB-2155 Leaf Debris Blower ES-2...,[],18.26,[{'thumb': 'https://m.media-amazon.com/images/...,[],AISEN,"[Patio, Lawn & Garden, Outdoor Power Tools, Re...",{'Package Dimensions': '4.57 x 3.03 x 1.34 inc...,B074C2TTV8,NaN
1,Amazon Home,Orbit 57946 B-hyve Smart 6-Zone Indoor/Outdoor...,4.5,12815,[WELCOME TO B-HYVE: Looking to get a smart spr...,"[From the manufacturer, Orbit is North America...",99.17,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Most affordable Smart Home Sprinkl...,Orbit,"[Patio, Lawn & Garden, Gardening & Lawn Care, ...","{'Product Dimensions': '3 x 9 x 8 inches', 'It...",B0BCZK8S44,NaN
2,Amazon Home,KafePross Merry Monogram M Decorative Garden F...,4.1,9,"[Mini garden flag (size: 12.5"" x 18"") are made...","[KafePross have a lot of flag design, there ar...",9.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],KafePross,"[Patio, Lawn & Garden, Outdoor Décor, Flags]",{'Package Dimensions': '9.37 x 6.14 x 0.47 inc...,B08K362CRS,NaN
3,Amazon Home,Kwik Covers 8' Rectangle Plastic Table Covers ...,4.5,346,[Kwik-Covers are hygienic table covers and dis...,"[8' x 30"" Kwik-Cover is a lightweight, elastic...",35.95,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Take a closer look at the table co...,Kwik Covers,"[Patio, Lawn & Garden, Patio Furniture & Acces...","{'Brand': 'Kwik Covers', 'Color': 'Orange', 'M...",B06XVX7YQT,NaN
4,Amazon Home,Agfabric Plant Cover Warm Worth Frost Blanket ...,3.1,3,[SUITABLE SIZE Perfect for Greenhouse size 90'...,[Agfabric Plant cover made with high quality s...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Agfabric,"[Patio, Lawn & Garden, Gardening & Lawn Care, ...",{'Package Dimensions': '15.98 x 12.99 x 4.02 i...,B01I9NNPYW,NaN

## Read the Data (Full)

In [ ]:
# TODO: Figure out what columns are actually needed, do NOT run this yet
# reviews_df = pd.read_json("../data/raw/Patio_Lawn_and_Garden.jsonl", lines = True)
# metadata_df = pd.read_json("../data/raw/meta_Patio_Lawn_and_Garden.jsonl", lines = True)